# Form implementation generated from reading ui file 'd:\documentos\Programacion avanzada\proyectos\Practica 6\nomunjugador.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Formulario1ju(object):
    def setupUi(self, Formulario1ju):
        Formulario1ju.setObjectName("Formulario1ju")
        Formulario1ju.resize(391, 169)
        Formulario1ju.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483318, y1:0.381, x2:0.438, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.636364 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.labelform = QtWidgets.QLabel(parent=Formulario1ju)
        self.labelform.setGeometry(QtCore.QRect(10, 40, 131, 41))
        self.labelform.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.labelform.setObjectName("labelform")
        self.nombre1p = QtWidgets.QTextEdit(parent=Formulario1ju)
        self.nombre1p.setGeometry(QtCore.QRect(150, 40, 231, 41))
        self.nombre1p.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
" border: 2px solid #ffffff;\n"
"\n"
"")
        self.nombre1p.setObjectName("nombre1p")
        self.boton1p = QtWidgets.QPushButton(parent=Formulario1ju)
        self.boton1p.setGeometry(QtCore.QRect(160, 110, 75, 24))
        self.boton1p.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
" border: 3px solid #ffffff;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgba(143,143,143,30);\n"
"border:40px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(143,143,143,90);\n"
"border:40px;\n"
"}")
        self.boton1p.setObjectName("boton1p")

        self.retranslateUi(Formulario1ju)
        QtCore.QMetaObject.connectSlotsByName(Formulario1ju)

    def retranslateUi(self, Formulario1ju):
        _translate = QtCore.QCoreApplication.translate
        Formulario1ju.setWindowTitle(_translate("Formulario1ju", "Form"))
        self.labelform.setText(_translate("Formulario1ju", "Name:"))
        self.boton1p.setText(_translate("Formulario1ju", "OK"))
        self.boton1p.setShortcut(_translate("Formulario1ju", "Return"))
