# Form implementation generated from reading ui file 'd:\documentos\Programacion avanzada\proyectos\Practica 6\ventana1jugador.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Unjugador(object):
    def setupUi(self, Unjugador):
        Unjugador.setObjectName("Unjugador")
        Unjugador.resize(448, 615)
        Unjugador.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483318, y1:0.381, x2:0.438, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.636364 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.star1p = QtWidgets.QPushButton(parent=Unjugador)
        self.star1p.setGeometry(QtCore.QRect(170, 320, 91, 31))
        self.star1p.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
"border: 3px solid #b80205;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,0,0,90);\n"
"border:40px;\n"
"}\n"
"")
        self.star1p.setObjectName("star1p")
        self.pause1p = QtWidgets.QPushButton(parent=Unjugador)
        self.pause1p.setGeometry(QtCore.QRect(170, 380, 91, 31))
        self.pause1p.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
"border: 3px solid #03ff2d;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(3,255,45,90);\n"
"border:40px;\n"
"}")
        self.pause1p.setObjectName("pause1p")
        self.return1p_2 = QtWidgets.QPushButton(parent=Unjugador)
        self.return1p_2.setGeometry(QtCore.QRect(170, 440, 91, 31))
        self.return1p_2.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
"border: 3px solid #ffff01;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,1,90);\n"
"border:40px;\n"
"}")
        self.return1p_2.setObjectName("return1p_2")
        self.groupBox = QtWidgets.QGroupBox(parent=Unjugador)
        self.groupBox.setGeometry(QtCore.QRect(30, 80, 381, 221))
        self.groupBox.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
" border: 3px solid #1723ff;\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 131, 31))
        self.label.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.nom1p = QtWidgets.QLabel(parent=self.groupBox)
        self.nom1p.setGeometry(QtCore.QRect(10, 90, 131, 31))
        self.nom1p.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.nom1p.setText("")
        self.nom1p.setObjectName("nom1p")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 131, 31))
        self.label_3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(220, 30, 131, 31))
        self.label_2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.score1p = QtWidgets.QLabel(parent=self.groupBox)
        self.score1p.setGeometry(QtCore.QRect(220, 90, 131, 31))
        self.score1p.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.score1p.setObjectName("score1p")
        self.ronda1p = QtWidgets.QLabel(parent=self.groupBox)
        self.ronda1p.setGeometry(QtCore.QRect(220, 150, 131, 31))
        self.ronda1p.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.ronda1p.setText("")
        self.ronda1p.setObjectName("ronda1p")
        self.Un_jugador = QtWidgets.QPushButton(parent=Unjugador)
        self.Un_jugador.setGeometry(QtCore.QRect(70, 10, 301, 61))
        self.Un_jugador.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 24pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"color: rgb(17, 107, 191);\n"
" \n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color:rgba(0,0,255,30);\n"
"border:40px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(0,0,255,90);\n"
"border:40px;\n"
"}")
        self.Un_jugador.setObjectName("Un_jugador")

        self.retranslateUi(Unjugador)
        QtCore.QMetaObject.connectSlotsByName(Unjugador)

    def retranslateUi(self, Unjugador):
        _translate = QtCore.QCoreApplication.translate
        Unjugador.setWindowTitle(_translate("Unjugador", "Un jugador"))
        self.star1p.setText(_translate("Unjugador", "Start"))
        self.pause1p.setText(_translate("Unjugador", "Pause"))
        self.return1p_2.setText(_translate("Unjugador", "Close Game"))
        self.label.setText(_translate("Unjugador", "Name"))
        self.label_3.setText(_translate("Unjugador", "Ronda"))
        self.label_2.setText(_translate("Unjugador", "Score"))
        self.score1p.setText(_translate("Unjugador", "000000"))
        self.Un_jugador.setText(_translate("Unjugador", "1 player"))
