# Form implementation generated from reading ui file 'd:\documentos\Programacion avanzada\proyectos\Practica 6\xtremo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_xtremo(object):
    def setupUi(self, xtremo):
        xtremo.setObjectName("xtremo")
        xtremo.resize(557, 707)
        xtremo.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483318, y1:0.381, x2:0.438, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.636364 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.textBrowser = QtWidgets.QTextBrowser(parent=xtremo)
        self.textBrowser.setGeometry(QtCore.QRect(130, 10, 271, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 24pt \"Impact\";\n"
"border:40px;\n"
"font-color:rgb(255,0,0);\n"
"\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.label_9 = QtWidgets.QLabel(parent=xtremo)
        self.label_9.setGeometry(QtCore.QRect(120, 340, 141, 31))
        self.label_9.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
" border: 3px solid #1723ff;\n"
"")
        self.label_9.setObjectName("label_9")
        self.turno = QtWidgets.QLabel(parent=xtremo)
        self.turno.setGeometry(QtCore.QRect(280, 340, 141, 31))
        self.turno.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
" border: 3px solid #1723ff;\n"
"")
        self.turno.setText("")
        self.turno.setObjectName("turno")
        self.groupBox = QtWidgets.QGroupBox(parent=xtremo)
        self.groupBox.setGeometry(QtCore.QRect(30, 80, 481, 241))
        self.groupBox.setStyleSheet("background-color: rgb(0,0, 0);\n"
"\n"
" border: 3px solid #ff0512;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.label_3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 81, 21))
        self.label_2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(410, 60, 51, 21))
        self.label_8.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_8.setObjectName("label_8")
        self.nomp1 = QtWidgets.QLabel(parent=self.groupBox)
        self.nomp1.setGeometry(QtCore.QRect(10, 40, 141, 21))
        self.nomp1.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.nomp1.setText("")
        self.nomp1.setObjectName("nomp1")
        self.nomp2 = QtWidgets.QLabel(parent=self.groupBox)
        self.nomp2.setGeometry(QtCore.QRect(10, 70, 141, 21))
        self.nomp2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.nomp2.setText("")
        self.nomp2.setObjectName("nomp2")
        self.nomp3 = QtWidgets.QLabel(parent=self.groupBox)
        self.nomp3.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.nomp3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.nomp3.setText("")
        self.nomp3.setObjectName("nomp3")
        self.nomp4 = QtWidgets.QLabel(parent=self.groupBox)
        self.nomp4.setGeometry(QtCore.QRect(10, 130, 141, 21))
        self.nomp4.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.nomp4.setText("")
        self.nomp4.setObjectName("nomp4")
        self.nomp5 = QtWidgets.QLabel(parent=self.groupBox)
        self.nomp5.setGeometry(QtCore.QRect(10, 160, 141, 21))
        self.nomp5.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.nomp5.setText("")
        self.nomp5.setObjectName("nomp5")
        self.nomp6 = QtWidgets.QLabel(parent=self.groupBox)
        self.nomp6.setGeometry(QtCore.QRect(10, 190, 141, 21))
        self.nomp6.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.nomp6.setText("")
        self.nomp6.setObjectName("nomp6")
        self.scp1 = QtWidgets.QLabel(parent=self.groupBox)
        self.scp1.setGeometry(QtCore.QRect(160, 40, 81, 21))
        self.scp1.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.scp1.setText("")
        self.scp1.setObjectName("scp1")
        self.round = QtWidgets.QLabel(parent=self.groupBox)
        self.round.setGeometry(QtCore.QRect(400, 100, 71, 21))
        self.round.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.round.setText("")
        self.round.setObjectName("round")
        self.scp2 = QtWidgets.QLabel(parent=self.groupBox)
        self.scp2.setGeometry(QtCore.QRect(160, 70, 81, 21))
        self.scp2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.scp2.setText("")
        self.scp2.setObjectName("scp2")
        self.scp3 = QtWidgets.QLabel(parent=self.groupBox)
        self.scp3.setGeometry(QtCore.QRect(160, 100, 81, 21))
        self.scp3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.scp3.setText("")
        self.scp3.setObjectName("scp3")
        self.scp4 = QtWidgets.QLabel(parent=self.groupBox)
        self.scp4.setGeometry(QtCore.QRect(160, 130, 81, 21))
        self.scp4.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.scp4.setText("")
        self.scp4.setObjectName("scp4")
        self.scp5 = QtWidgets.QLabel(parent=self.groupBox)
        self.scp5.setGeometry(QtCore.QRect(160, 160, 81, 21))
        self.scp5.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.scp5.setText("")
        self.scp5.setObjectName("scp5")
        self.scp6 = QtWidgets.QLabel(parent=self.groupBox)
        self.scp6.setGeometry(QtCore.QRect(160, 190, 81, 21))
        self.scp6.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.scp6.setText("")
        self.scp6.setObjectName("scp6")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(260, 10, 81, 21))
        self.label_19.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_19.setObjectName("label_19")
        self.stp1 = QtWidgets.QLabel(parent=self.groupBox)
        self.stp1.setGeometry(QtCore.QRect(240, 40, 141, 21))
        self.stp1.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.stp1.setText("")
        self.stp1.setObjectName("stp1")
        self.stp2 = QtWidgets.QLabel(parent=self.groupBox)
        self.stp2.setGeometry(QtCore.QRect(240, 70, 141, 21))
        self.stp2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.stp2.setText("")
        self.stp2.setObjectName("stp2")
        self.stp3 = QtWidgets.QLabel(parent=self.groupBox)
        self.stp3.setGeometry(QtCore.QRect(240, 100, 141, 21))
        self.stp3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.stp3.setText("")
        self.stp3.setObjectName("stp3")
        self.stp4 = QtWidgets.QLabel(parent=self.groupBox)
        self.stp4.setGeometry(QtCore.QRect(240, 130, 141, 21))
        self.stp4.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.stp4.setText("")
        self.stp4.setObjectName("stp4")
        self.stp5 = QtWidgets.QLabel(parent=self.groupBox)
        self.stp5.setGeometry(QtCore.QRect(240, 160, 141, 21))
        self.stp5.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.stp5.setText("")
        self.stp5.setObjectName("stp5")
        self.stp6 = QtWidgets.QLabel(parent=self.groupBox)
        self.stp6.setGeometry(QtCore.QRect(240, 190, 141, 21))
        self.stp6.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.stp6.setText("")
        self.stp6.setObjectName("stp6")
        self.pausex = QtWidgets.QPushButton(parent=xtremo)
        self.pausex.setGeometry(QtCore.QRect(230, 440, 91, 31))
        self.pausex.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
"border: 3px solid #03ff2d;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(3,255,45,90);\n"
"border:40px;\n"
"}")
        self.pausex.setObjectName("pausex")
        self.returnx = QtWidgets.QPushButton(parent=xtremo)
        self.returnx.setGeometry(QtCore.QRect(230, 490, 91, 31))
        self.returnx.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
"border: 3px solid #ffff01;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,1,90);\n"
"border:40px;\n"
"}")
        self.returnx.setObjectName("returnx")
        self.starx = QtWidgets.QPushButton(parent=xtremo)
        self.starx.setGeometry(QtCore.QRect(230, 390, 91, 31))
        self.starx.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
"border: 3px solid #b80205;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,0,0,90);\n"
"border:40px;\n"
"}\n"
"")
        self.starx.setObjectName("starx")

        self.retranslateUi(xtremo)
        QtCore.QMetaObject.connectSlotsByName(xtremo)

    def retranslateUi(self, xtremo):
        _translate = QtCore.QCoreApplication.translate
        xtremo.setWindowTitle(_translate("xtremo", "Form"))
        self.textBrowser.setHtml(_translate("xtremo", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Impact\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0224;\">Xtream</span></p></body></html>"))
        self.label_9.setText(_translate("xtremo", "Turn"))
        self.label_3.setText(_translate("xtremo", "Players"))
        self.label_2.setText(_translate("xtremo", "Score"))
        self.label_8.setText(_translate("xtremo", "Round"))
        self.label_19.setText(_translate("xtremo", "Status"))
        self.pausex.setText(_translate("xtremo", "Pause"))
        self.returnx.setText(_translate("xtremo", "Close Game"))
        self.starx.setText(_translate("xtremo", "Start"))
