# Form implementation generated from reading ui file 'd:\documentos\Programacion avanzada\proyectos\Practica 6\xjugadores.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_xjugadores(object):
    def setupUi(self, xjugadores):
        xjugadores.setObjectName("xjugadores")
        xjugadores.resize(460, 436)
        xjugadores.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.483318, y1:0.381, x2:0.438, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.636364 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label = QtWidgets.QLabel(parent=xjugadores)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 21))
        self.label.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.select = QtWidgets.QSpinBox(parent=xjugadores)
        self.select.setGeometry(QtCore.QRect(180, 10, 221, 41))
        self.select.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.select.setMinimum(1)
        self.select.setMaximum(6)
        self.select.setObjectName("select")
        self.Player1 = QtWidgets.QLabel(parent=xjugadores)
        self.Player1.setEnabled(True)
        self.Player1.setGeometry(QtCore.QRect(20, 60, 141, 21))
        self.Player1.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.Player1.setObjectName("Player1")
        self.Player2 = QtWidgets.QLabel(parent=xjugadores)
        self.Player2.setGeometry(QtCore.QRect(20, 100, 141, 21))
        self.Player2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Player2.setObjectName("Player2")
        self.Player3 = QtWidgets.QLabel(parent=xjugadores)
        self.Player3.setGeometry(QtCore.QRect(20, 140, 141, 21))
        self.Player3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Player3.setObjectName("Player3")
        self.Player4 = QtWidgets.QLabel(parent=xjugadores)
        self.Player4.setGeometry(QtCore.QRect(20, 180, 141, 21))
        self.Player4.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Player4.setObjectName("Player4")
        self.Player5 = QtWidgets.QLabel(parent=xjugadores)
        self.Player5.setGeometry(QtCore.QRect(20, 220, 141, 21))
        self.Player5.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Player5.setObjectName("Player5")
        self.Player6 = QtWidgets.QLabel(parent=xjugadores)
        self.Player6.setGeometry(QtCore.QRect(20, 260, 141, 21))
        self.Player6.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Player6.setObjectName("Player6")
        self.nomPlayer1 = QtWidgets.QTextEdit(parent=xjugadores)
        self.nomPlayer1.setGeometry(QtCore.QRect(180, 60, 231, 31))
        self.nomPlayer1.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"  border: 2px solid #1723ff;\n"
"\n"
"\n"
"")
        self.nomPlayer1.setObjectName("nomPlayer1")
        self.nomPlayer2 = QtWidgets.QTextEdit(parent=xjugadores)
        self.nomPlayer2.setGeometry(QtCore.QRect(180, 100, 231, 31))
        self.nomPlayer2.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid #b80205;\n"
"\n"
"")
        self.nomPlayer2.setObjectName("nomPlayer2")
        self.nomPlayer3 = QtWidgets.QTextEdit(parent=xjugadores)
        self.nomPlayer3.setGeometry(QtCore.QRect(180, 140, 231, 31))
        self.nomPlayer3.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid #03ff2d;\n"
"\n"
"")
        self.nomPlayer3.setObjectName("nomPlayer3")
        self.nomPlayer4 = QtWidgets.QTextEdit(parent=xjugadores)
        self.nomPlayer4.setGeometry(QtCore.QRect(180, 180, 231, 31))
        self.nomPlayer4.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid #ffff01;\n"
"")
        self.nomPlayer4.setObjectName("nomPlayer4")
        self.nomPlayer5 = QtWidgets.QTextEdit(parent=xjugadores)
        self.nomPlayer5.setGeometry(QtCore.QRect(180, 220, 231, 31))
        self.nomPlayer5.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
" border: 2px solid #1723ff;\n"
"")
        self.nomPlayer5.setObjectName("nomPlayer5")
        self.nomPlayer6 = QtWidgets.QTextEdit(parent=xjugadores)
        self.nomPlayer6.setGeometry(QtCore.QRect(180, 260, 231, 31))
        self.nomPlayer6.setStyleSheet("background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid #b80205;\n"
"\n"
"")
        self.nomPlayer6.setObjectName("nomPlayer6")
        self.check = QtWidgets.QPushButton(parent=xjugadores)
        self.check.setGeometry(QtCore.QRect(420, 13, 31, 31))
        self.check.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
" border: 3px solid #ffffff;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgba(143,143,143,30);\n"
"border:40px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(143,143,143,90);\n"
"border:40px;\n"
"}")
        self.check.setObjectName("check")
        self.conf = QtWidgets.QPushButton(parent=xjugadores)
        self.conf.setGeometry(QtCore.QRect(180, 320, 91, 31))
        self.conf.setStyleSheet("QPushButton\n"
"{background-color: rgb(0,0, 0);\n"
"font: 12pt \"Impact\";\n"
"border:40px;\n"
"font-color:white;\n"
"    color: rgb(255, 255, 255);\n"
" border: 3px solid #ffffff;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgba(143,143,143,30);\n"
"border:40px;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(143,143,143,90);\n"
"border:40px;\n"
"}")
        self.conf.setObjectName("conf")

        self.retranslateUi(xjugadores)
        QtCore.QMetaObject.connectSlotsByName(xjugadores)

    def retranslateUi(self, xjugadores):
        _translate = QtCore.QCoreApplication.translate
        xjugadores.setWindowTitle(_translate("xjugadores", "Form"))
        self.label.setText(_translate("xjugadores", "Players"))
        self.Player1.setText(_translate("xjugadores", "Player 1"))
        self.Player2.setText(_translate("xjugadores", "Player 2"))
        self.Player3.setText(_translate("xjugadores", "Player 3"))
        self.Player4.setText(_translate("xjugadores", "Player 4"))
        self.Player5.setText(_translate("xjugadores", "Player 5"))
        self.Player6.setText(_translate("xjugadores", "Player 6"))
        self.check.setText(_translate("xjugadores", "✔"))
        self.check.setShortcut(_translate("xjugadores", "Return"))
        self.conf.setText(_translate("xjugadores", "Confirm"))
        self.conf.setShortcut(_translate("xjugadores", "Return"))
